export const ROUTE = {
  MAINPAGE: '/',
  LOGINPAGE: '/login',
  SIGNUPPAGE: '/signup',
  DETAILPAGE: '/detail/:productId',
  MYPAGE: '/mypage/:userId',
  SHOPPINGCART: '/shoppingcart/:userId',
  ADDRESSINPUTPAGE: '/addressinput/:userId',
  PAYMENTCONFIRMATIONPAGE: '/paymentconfirm/:userId',
  CHECKOUTPAGE: '/checkout',
  SUCCESSPAGE: '/success',
  FAILPAGE: '/fail',
  REGISTERMYPET: '/registermypet/:userId/:step',
  NOTFOUND: '*',
} as const;
