import { IProductInfo } from '@types';

export const ProductInfo: IProductInfo[] = [
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
  {
    productId: 1,
    category: {
      categoryId: 1,
      categoryName: '사료',
    },
    productName: '강아지 사료 1kg',
    seller: {
      sellerId: 100,
      sellerStoreName: '멍멍이네',
      sellerNumber: '02-1234-5678',
      sellerAddr: '서울시 강남구',
      sellerAddrDetail: '역삼동 123-45',
    },
    productStatus: 'ON',
    productPrice: 25000,
    productSale: 0,
    productCnt: 100,
    productThumbnail: 'https://via.placeholder.com/200',
  },
];
